use_frameworks!

platform :ios, '10.0'

target 'popup-bottom-navigation_Example' do
  pod 'popup-bottom-navigation', :path => '../'

  target 'popup-bottom-navigation_Tests' do
    inherit! :search_paths

    
  end
end
