use_frameworks!

platform :ios, '10.0'

target 'PopupBottomNavigation_Example' do
  pod 'PopupBottomNavigation', :path => '../'

  target 'PopupBottomNavigation_Tests' do
    inherit! :search_paths

    
  end
end
